### PR TITLE
Changes

### PR DESCRIPTION
**Pull request by zen0bit**
In preparation for TUI
Some changes for me to be slightly easier to read

### CODE REVIEW

**Comment by ivan-hc** [comment]
Hi, I thank you for this cleaning job, but unfortunately I have to refuse this PR.

The reasons are simple:
- if you compare the "[AppMan](https://github.com/ivan-hc/AppMan/blob/main/appman)" file with the "[AM](https://github.com/ivan-hc/AM-Application-Manager/blob/main/APP-MANAGER)" one, you will notice very few differences, because in fact they are almost the same thing (AppMan contains additional steps to convert AM scripts, see https://www.diffchecker.com/p4VV3dfg/ ), if you compare the commits to the individual files ([commits of AppMan](https://github.com/ivan-hc/AppMan/commits/main/appman) vs [commits of AM](https://github.com/ivan-hc/AM-Application-Manager/commits/main/APP-MANAGER)), you will notice that they were released almost simultaneously and that they are copies of each other;
- given the previous reason, "AM" has already undergone this type of cleaning several months ago [by another user](https://github.com/ivan-hc/AM-Application-Manager/commits?author=DLopezJr), so if I have satisfied the style of a developer, I cannot do the same in the future to avoid problems with modifications to the two files.

I appreciate the effort, but I can't slow down the development of the two programs because I have to figure out what to change in AppMan to make it do the things AM does.

**Comment by zen0bit** [comment]
i saw a lot of common for both and i think it could easily become one app instead...

**Comment by ivan-hc** [comment]
Indeed, but they have different installation methods. "AM" must work into a system's $PATH to use /opt, AppMan on the other hand works wherever you want to put it and does not require sudo.

**Comment by zen0bit** [comment]
only difference?

**Comment by ivan-hc** [comment]
@zen0bit It would make sense to make them one thing, but while "AM" is meant to be used by all users, AppMan is meant for those who use a GNU/Linux system with multiple accounts.

Features like "bash-completion" would only work for a single user of the same PC if you made AM as portable as AppMan, and the configurations themselves would be different between users. Their dual existence has a sense of being there.

AppMan was the first program I built, initially it installed all programs in a /opt/bin folder, including program subfolders, but this mode conflicted with LSB (Linux Standard Base), and I couldn't override the entire project to correct this problem. I received a lot of criticism for this choice, so I initially abandoned AppMan to invest all my work in AM.

When AM started to gain some popularity,  there were people who wanted to use AM locally, and I couldn't twist it as well as I had done for AppMan. Linux users have different needs, see the amount of various desktop environments (GNOME, KDE, XFCE...). There is no common need. A project must be split in two to satisfy multiple parties.

I started rewriting AppMan to get the result you know today, now it's a portable solution and anyone can use it in any directory they want (so as not to impose a location... and to avoid more pain in the ass like the ones you just read) .

But the years pass, the standards are always changed, and with the arrival of new distributions (see the immutable distros that do not allow you to modify /usr) one program must necessarily update itself to support the other (see the option --user of AM).

The day the distros stop supporting the AppImage format, I will have to be ready to correct that problem too, and to do so I must necessarily keep the two codes as similar as possible to each other, in order to speed up the workflow.

That's all.

**Comment by ivan-hc** [comment]
For example, I'm an AM user because I want third-party apps in the /opt folder (as directed by LSB) and I don't want anything in my $HOME. I see installed programs and user data as things that need to be separated from each other.

Those who use AppMan, on the other hand, want to save only the $HOME folder in case of backups and various formatting of the system, which from my point of view is very practical, but also too resource-intensive (I can re-download the programs).

**Comment by zen0bit** [comment]
I am just dont see purpose for keeping two separate programs which doing 99% the same. could be easily achieved in one program just with few variables...

also what about using more functions in script?

white space and indentation cleanup?

I already did that...

**Comment by ivan-hc** [comment]
@zen0bit I tried your modification of AM, however there would be too much work to do. I don't see the need for it. AM must be oriented towards a fixed installation, AppMan must be portable. I've already thought about how I could combine the two projects, but that's not my priority. Let alone having to clean the white spaces from one script to another, as I am the maintainer, I would only have confusion before my eyes and terrible headaches (I did everything to bring AM and AppMan to the same level).

In the future I will certainly be able to make improvements to AM making it both an installable and portable app... but now it is not a priority: while we are discussing here, the YouTube channel TheLinuxExperiment has just published a [video](https://www.youtube.com/watch?v=ikBPnYwnUMU) on the various packaging formats, and the AppImages have them considered an option "not worthy of consideration", for his tastes. This means that for the umpteenth time, from 2020 to today, my effort to make AppImage a better packaging format has been a failure! I can't think about cleaning up the code now, there are too many people who don't know about the existence of this package MANAGEMENT method that I've been working on for 3 years. The result? More and more distributions abandon the use of libfuse2, nor is there interest in including AppImage support in general, not even Wayland seems to support them, and the focus is more and more on Flatpak.

Appimages are destined to disappear at this rate! If my efforts remain in the shadow, all this work will be completely useless!

Furthermore, soon I will start working in some supermarket again (I'm not a developer, I enjoy writing Shell scripts in my free time) and the hours will be almost completely non-permissive, and I will have to start staying away from my projects, again, to dedicate myself to something else in real life.

The last option I created, "--launcher", serves to partially replace the work that AppimageLauncher or GearLever would do, since most Linux users know that AppImages work like this.

I have a database of over 1800 installation scripts, but AppimageHub is still the one-stop shop for them all.

Even DistroTube on Youtube wasn't much help, at the time of the [review](https://www.youtube.com/watch?v=7SfDlR3vU3I) it was using a version full of bugs and one year old, then by running the "am -u" command it went from version 3.0.6 to 4.x (not I remember which version) which had different functionality. Seeing that video, I realized that he reviewed yet another useless and amateurish program to please an annoying Reddit spammer (me).

Having said that, it is better to leave AM and AppMan as they are, because they are two scripts that work and are stable (at present). They each do what they were written to do. They have one flaw: they don't have a graphical interface.

If you want to help me, don't ask me for code twists. I modified the page https://portable-linux-apps.github.io/apps.html to include a "raw" installation script. A "grep" command could very well intercept the link and activate the installation of the app, or display the list of apps with the -l and -q options... basically an Electron frontend could do the same job as an app like " App Outlet". This is the kind of work I'm interested in right now, but even an app in YAD or Python or QT... it's all great. Unfortunately I don't have all this time to study new programming languages, due to work and family issues.

I have given a basis, as the developer of this project I don't see the need to upset everything now that the scripts are working. What I see instead is all negative. Developers are stopping creating AppImages, sometimes deleting them from their artifact history, and all in favor of Flatpak. Flathub has an "Install" button that downloads the .flatpakref file for which there is also an extension available in all browsers that allows you to install Flatpaks with just one click. You could do the same with the links to the "raw" I provided on that page I linked above.

Try to understand my disappointment. Thank you.

**Pull request closed without merging**
